FROM debian:latest

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get -y upgrade && \
	 apt-get -y install sudo && \
	 apt-get -y install curl && \
	 apt-get -y install npm
RUN curl --silent --location https://deb.nodesource.com/setup_14.x  | sudo -E bash -
RUN sudo apt-get install --assume-yes nodejs

COPY . ./deltachat-desktop
WORKDIR ./deltachat-desktop
